config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "pages#home"

  get "dashboard", to: "pages#dashboard", as: "dashboard"

  resource :registration, only: [ :new, :create ]

  resources :books, only: [:index, :show]

  resources :borrowing_records, only: [ :create, :update ]

  resource :profile, only: [ :show ], controller: "users"
end

app/views/pages/dashboard.html.erb
<h1 class="text-2xl mt-2 mb-10"> Welcome, <%= Current.user.email_address.split("@").first.capitalize %>! </h1>


<!--Borrowed Books-->
<section>

  <div class="flex justify-between">
    <h2 class="text-2xl font-semibold mb-4">Some Of Your Borrowed Books</h2>

    <div class="flex">
      <%= link_to "View All", profile_path, class: "mr-4" %>
      <%= render "shared/arrow_icon" %>
    </div>
  </div>
  <% if @borrowed_books.any? %>
    <div class="space-y-4 flex flex-wrap justify-between">
      <% @borrowed_books.first(4).each do |book| %>
        <% borrowing_record = book.borrowing_records.find_by(returned_at: nil) %>
        <div class="flex flex-col justify-between">

          <%= render partial: "books/book_card", locals: {book: book.book} %>

          <%= render partial: "shared/due_date", locals: {due_date: borrowing_record.due_date} %>

          <%#= button_to "Return Book", borrowing_record_path(borrowing_record), method: :patch, class: "bg-black text-white px-4 py-2 rounded-md font-semibold hover:opacity-90 transition mt-4 block text-center" %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-500">You have no borrowed books.</p>
  <% end %>

</section>


<!--Some of the available books-->
<section class="mt-10">
  <div class="flex justify-between">
    <h2 class="text-2xl font-semibold mb-4">Available Books</h2>

    <div class="flex">
      <%= link_to "View All", books_path, class: "mr-4" %>
      <%= render "shared/arrow_icon" %>
    </div>
  </div>
<% if @available_books.any? %>
  <div class="flex flex-wrap justify-between">
    <% @available_books.first(4).each do |book| %>
      <div class="">
        <%= render partial: "books/book_card", locals: {book: book} %>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="text-gray-500">No books available right now.</p>
<% end %>
</section>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= content_for(:title) || "Bland" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<main class="min-h-screen max-w-screen-xl mx-auto flex flex-col px-6">

  <!--  Nav-->
  <nav class="flex items-center py-4">
    <h1 class="text-5xl font-bold">Bland</h1>
    <%= link_to "Login", new_session_path,  class: "block ml-auto m-2 pointer" %>
  </nav>

  <!--  Container-->
  <div class="flex-grow flex flex-col items-center justify-center md:flex-row gap-10">

    <div class="text-center md:w-1/3 md:text-left">
      <h2 class="text-6xl font-bold mb-10">Find Your Next Book</h2>
      <p class="mb-10">We've got everything for everyone</p>
      <%= link_to "Get Started", new_registration_path, class: "inline-block font-bold px-6 py-3 bg-black text-white mt-12 md:w-auto" %>
    </div>

    <div class="hidden md:flex md:w-2/3 justify-around gap-10 relative">
      <%= image_tag "read.jpg", alt: "A book cover", class: "w-1/4 h-80 object-cover rounded-t-full" %>
      <%= image_tag "soul.jpg", alt: "A book cover", class: "w-1/4 h-80 object-cover rounded-b-full" %>
      <%= image_tag "milk_honey.jpg", alt: "A book cover", class: "w-1/4 h-80 object-cover rounded-t-full" %>
    </div>

  </div>

</main>
</body>
</html>