config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "pages#home"

  get "dashboard", to: "pages#dashboard", as: "dashboard"

  resource :registration, only: [ :new, :create ]

  resources :books, only: [:index, :show]

  resources :borrowing_records, only: [ :create, :update ]

  resource :profile, only: [ :show ], controller: "users"
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :borrowing_records, dependent: :destroy
  has_many :users, through: :borrowing_records
  has_many :book_copies

  validates :title, presence: true
  validates :author, presence: true
  validates :isbn, presence: true, uniqueness: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end


  def show
    @book = Book.find(params[:id])

    @total_copies = @book.book_copies.count
    @available_copies = @book.book_copies.where(status: "available").count
    @user_borrowing_record = Current.user.borrowing_records.find_by(book_copy: @book.book_copies, returned_at: nil)
    @available_copy = @book.book_copies.find_by(status: "available") # Find the first available book copy
  end
end

app/views/books/_book_card.html.erb
<%= link_to book_path(book), class: "m-2 block w-56" do %>

  <div class="h-64 bg-black flex items-center justify-center">
    <p class="text-white font-bold">
      <%= book.title %>
    </p>
  </div>
  <div class="flex justify-between items-center">
    <div class="">
      <p class="text-lg font-semibold mt-3">
        <%= book.title %>
      </p>
      <p class="text-sm text-gray-600">
        <%= book.author %>
      </p>
    </div>
    <%= render "shared/arrow_top_right_icon" %>
  </div>

<% end %>

app/views/books/index.html.erb
<div class="flex flex-wrap gap-10 mt-20 ">


  <% if @books.any? %>

  <% @books.each do |book| %>

   <%= render partial: "books/book_card", locals: {book: book} %>



  <% end %>

<% else %>

  <p>No books available</p>

<% end %>

</div>

app/views/books/show.html.erb
<div class="mt-20 flex flex-col md:flex-row md:items-start md:justify-center md:gap-12">

<!--  Book Cover and details-->
  <div class="flex flex-col items-center md:items-start text-center md:text-left">
    <!-- Book Cover -->
    <div class="w-56 h-72 bg-black text-white flex justify-center items-center rounded-lg shadow-lg">
      <p class="text-lg font-semibold text-center px-3">
        <%= @book.title %>
      </p>
    </div>

    <p class="text-2xl font-semibold mt-4">
      <%= @book.title %>
    </p>
    <p class="text-gray-600 mt-2">
      By <span class="font-bold"> <%= @book.author %> </span>
    </p>
    <p class="text-xs text-gray-500 mt-2">
      ISBN: <%= @book.isbn %>
    </p>

  </div>

  <!-- Available copies -->
  <p class="mt-4 text-gray-600">
    <%= @available_copies %> out of <%= @total_copies %> copies are available.
  </p>

  <% if @user_borrowing_record %>
    <p class="text-sm text-gray-500">You have already borrowed a copy of this book.</p>
    <%= button_to "Return Book", borrowing_record_path(@user_borrowing_record), method: :patch, class: "bg-red-600 text-white px-4 py-2 rounded-md font-semibold hover:bg-red-700" %>
  <% elsif @available_copy %>
    <%= button_to "Borrow", borrowing_records_path(book_copy_id: @available_copy.id), method: :post, class: "bg-black text-white px-4 py-2 rounded-md font-semibold hover:opacity-90 transition" %>
  <% else %>
    <p class="text-sm text-gray-500">📚 There are no available copies to borrow.</p>
  <% end %>




</div>