config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "pages#home"

  get "dashboard", to: "pages#dashboard", as: "dashboard"

  resource :registration, only: [ :new, :create ]

  resources :books, only: [:index, :show]

  resources :borrowing_records, only: [ :create, :update ]

  resource :profile, only: [ :show ], controller: "users"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bland" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <main class="min-h-screen max-w-screen-xl mx-auto flex flex-col px-6">
        <nav class="flex items-center py-4">
<!--          Logo-->
          <%= link_to "Bland", root_path, class: "text-5xl font-bold" %>

<!--          Nav links-->
          <div class="flex space-x-6 ml-auto mr-auto">
            <%= link_to "Dashboard", dashboard_path, class: "font-bold text-gray-800 hover:text-gray-400 transition px-2 #{'text-gray-600 border-b-2 border-gray-800' if current_page?(dashboard_path)}" %>

            <%= link_to "All Books", books_path, class: "font-bold text-gray-800 hover:text-gray-400 transition px-2 #{'text-gray-600 border-b-2 border-gray-800' if current_page?(books_path)}" %>

            <%= link_to "Profile", profile_path, class: "font-bold text-gray-800 hover:text-gray-400 transition px-2 #{'text-gray-600 border-b-2 border-gray-800' if current_page?(profile_path)}" %>
          </div>

<!--          Log out button-->
          <% if Current.user.present? %>
            <%= button_to "Log out", session_path, method: :delete, class: "font-bold text-white bg-black px-4 py-2 rounded-lg ml-6 cursor-pointer hover:opacity-50 transition" %>
          <% end %>
        </nav>



        <div class="fixed top-20 left-1/2 transform -translate-x-1/2 z-50 w-auto">
          <% if flash[:alert] %>
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded shadow-lg text-center">
              <%= flash[:alert] %>
            </div>
          <% end %>

          <% if flash[:notice] %>
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded shadow-lg text-center">
              <%= flash[:notice] %>
            </div>
          <% end %>
        </div>


        <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/unauthenticated.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= content_for(:title) || "Bland" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<main class="min-h-screen max-w-screen-xl mx-auto flex flex-col px-6">

  <!--  Nav-->
  <nav class="flex items-center py-4">
    <%= link_to "Bland", root_path, class: "text-5xl font-bold" %>
    <% if request.path == new_session_path %>
      <%= link_to "Register", new_registration_path, class: "block ml-auto m-2 pointer" %>
    <% elsif request.path == new_registration_path %>
      <%= link_to "Login", new_session_path, class: "block ml-auto m-2 pointer" %>
    <% end %>
  </nav>

  <!--  Container-->
  <div class="flex-grow flex flex-col items-center justify-center gap-10 lg:w-1/2 mx-auto">

    <%= yield %>

  </div>

</main>
</body>
</html>